name: Build
#
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [ "self-hosted", "windows" ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Build .Net Project
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\devenv.com" .\${{ github.event.repository.name }}.sln /build "DEBUG|Any CPU" >> ..\BuildLogs.txt
          $buildlog = Get-Content "..\BuildLogs.txt" -tail 3
          Write-OutPut $buildlog
          if($buildlog.Contains("0 failed")){
            Exit 0
          }else{
            Exit 1
          }
          rm ..\BuildLogs.txt
